"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mn1d=6%+9-$yyn4ju+0!nhs0k10%hf4mvqjz!%w$ymzpv&2fqq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # 必须添加此应用
    # 自定义应用
    "apps.users",
    "apps.articles",
    "apps.comments",
    "utils.logs",  # 访问日志应用
    "utils.api",  # API应用
    "utils",
    # 第三方应用
    "rest_framework",
    "rest_framework_simplejwt",
    "markdown",
    "drf_yasg",  # Swagger文档
    "debug_toolbar",  # Django Debug Toolbar
    # django-allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",  # GitHub提供商
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Debug Toolbar中间件
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # django-allauth中间件
    "allauth.account.middleware.AccountMiddleware",
    # 自定义中间件
    "utils.logs.middleware.AccessLogMiddleware",  # 访问日志中间件
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# MySQL配置（暂时注释）
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "blog_os",
#         "USER": "ggtmy31755",
#         "PASSWORD": "123456789",  # 使用空密码登录
#         "HOST": "db4free.net",
#         "PORT": "3306",
#         "OPTIONS": {
#             "charset": "utf8mb4",
#         },
#     }
# }

# SQLite配置
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 改为中文

TIME_ZONE = "Asia/Shanghai"  # 改为中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 自定义用户模型
AUTH_USER_MODEL = "users.User"

# 登录和登出重定向URL
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# django-allauth配置
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Django默认的认证后端
    'django.contrib.auth.backends.ModelBackend',
    # django-allauth的认证后端
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 社交账号设置
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'APP': {
            'client_id': 'Ov23liDnrwEMQqWLTWJs',
            'secret': '85da38312e31fedfa2ae0dcf6ce105bdc206beed',
            'key': ''
        },
        'SCOPE': ['user:email'],
        'VERIFIED_EMAIL': True,
    }
}

# 允许用户在没有电子邮件的情况下使用社交账号登录
SOCIALACCOUNT_EMAIL_REQUIRED = False

# 允许用户使用多个社交账号关联到同一个本地账号
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

# 自动关联新用户
SOCIALACCOUNT_AUTO_SIGNUP = True

# 调试模式
SOCIALACCOUNT_STORE_TOKENS = True

# 日志级别 - 已删除有问题的配置

# 额外的allauth设置
# 新的配置格式
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'

# 媒体文件配置
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# REST Framework配置
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
}

# JWT配置
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# 邮件配置
# 开发环境使用控制台后端 - 启用此选项用于开发测试
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 生产环境使用SMTP后端
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.tjise.edu.cn"
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # 注意：端口465通常使用SSL而非TLS
EMAIL_HOST_USER = "2450310705@stu.tjise.edu.cn"
EMAIL_HOST_PASSWORD = "ZbpRDBa1d7Kzjpqy"

# 默认发件人邮箱
DEFAULT_FROM_EMAIL = "2450310705@stu.tjise.edu.cn"

# 站点URL，用于构建完整的URL
SITE_URL = "http://127.0.0.1:8000"

# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# 缓存过期时间设置
CACHE_TTL = 60 * 15  # 15分钟

# Celery配置
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Redis作为消息代理
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"  # Redis作为结果存储
CELERY_ACCEPT_CONTENT = ["json"]  # 指定接受的内容类型
CELERY_TASK_SERIALIZER = "json"  # 任务序列化和反序列化使用JSON
CELERY_RESULT_SERIALIZER = "json"  # 结果序列化为JSON
CELERY_TIMEZONE = TIME_ZONE  # 使用与Django相同的时区
CELERY_TASK_TIME_LIMIT = 30 * 60  # 任务硬超时时间为30分钟
CELERY_TASK_SOFT_TIME_LIMIT = 20 * 60  # 任务软超时时间为20分钟

# 导入Celery定时任务配置
from utils.celery.schedule import CELERY_BEAT_SCHEDULE

CELERY_BEAT_SCHEDULE = CELERY_BEAT_SCHEDULE

# 日志配置
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs/django.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "apps.logs": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Django Debug Toolbar配置
INTERNAL_IPS = [
    "127.0.0.1",
]

# Debug Toolbar设置
DEBUG_TOOLBAR_CONFIG = {
    # 默认隐藏工具栏，只在URL中添加__debug__=true参数时才显示
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG
    and request.GET.get("__debug__", "") == "true",
    # 允许在测试中使用Debug Toolbar
    "IS_RUNNING_TESTS": False,
}
