# Generated by Django 4.2.20 on 2025-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_like_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="别名"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="标签别名"),
        ),
    ]
