# Generated by Django 4.2.20 on 2025-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
