# Generated by Django 4.2.20 on 2025-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="发布时间"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                db_index=True,
                default="draft",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="浏览量"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="visibility",
            field=models.CharField(
                choices=[("public", "公开"), ("private", "私密")],
                db_index=True,
                default="public",
                max_length=10,
                verbose_name="可见性",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["author", "status"], name="author_status_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "visibility"], name="status_visibility_idx"
            ),
        ),
    ]
