# Generated by Django 4.2.20 on 2025-05-06 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "articles",
            "0005_alter_article_created_at_alter_article_published_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="日期"),
                ),
                (
                    "total_views",
                    models.PositiveIntegerField(default=0, verbose_name="总浏览量"),
                ),
                (
                    "total_likes",
                    models.PositiveIntegerField(default=0, verbose_name="总点赞数"),
                ),
                (
                    "total_favorites",
                    models.PositiveIntegerField(default=0, verbose_name="总收藏数"),
                ),
                (
                    "total_comments",
                    models.PositiveIntegerField(default=0, verbose_name="总评论数"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(default=0, verbose_name="活跃用户数"),
                ),
                (
                    "new_articles",
                    models.PositiveIntegerField(default=0, verbose_name="新文章数"),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("like_favorite", "点赞/收藏"),
                            ("post_comment", "发布/评论"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="活动日期",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="登录权重1，点赞/收藏权重2，发文章/评论权重3",
                        verbose_name="权重",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户活跃度",
                "verbose_name_plural": "用户活跃度",
                "ordering": ["-activity_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["activity_date"], name="activity_date_idx"),
                    models.Index(
                        fields=["user", "activity_date"], name="user_activity_date_idx"
                    ),
                ],
                "unique_together": {("user", "activity_date", "activity_type")},
            },
        ),
        migrations.CreateModel(
            name="ArticleStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "favorites_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章统计",
                "verbose_name_plural": "文章统计",
                "ordering": ["-views_count"],
                "indexes": [
                    models.Index(fields=["-views_count"], name="views_count_idx"),
                    models.Index(fields=["-likes_count"], name="likes_count_idx"),
                    models.Index(
                        fields=["-favorites_count"], name="favorites_count_idx"
                    ),
                    models.Index(fields=["-comments_count"], name="comments_count_idx"),
                ],
            },
        ),
    ]
