name: Main分支保护配置

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main-branch-protection.yml'

jobs:
  update-branch-protection:
    name: 更新分支保护规则
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置分支保护规则
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            try {
              // 获取仓库信息
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              
              // 设置分支保护规则
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'validate-pr',
                    'lint-and-test',
                    'security-check',
                    'integration-test'
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true,
                  required_approving_review_count: 1
                },
                restrictions: null,
                required_linear_history: true,
                allow_force_pushes: false,
                allow_deletions: false,
                required_conversation_resolution: true
              });
              
              console.log('Main分支保护规则已更新');
            } catch (error) {
              console.error('设置分支保护规则失败:', error);
              core.setFailed(error.message);
            }
      
      - name: 创建CODEOWNERS文件（如果不存在）
        run: |
          if [ ! -f ".github/CODEOWNERS" ]; then
            mkdir -p .github
            echo "# 代码所有者配置文件" > .github/CODEOWNERS
            echo "# 格式: 文件模式 @用户或组" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 默认拥有者" >> .github/CODEOWNERS
            echo "* @${{ github.repository_owner }}" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 用户模块所有者" >> .github/CODEOWNERS
            echo "/blog/apps/users/ @${{ github.repository_owner }}" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 文章模块所有者" >> .github/CODEOWNERS
            echo "/blog/apps/articles/ @${{ github.repository_owner }}" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 评论模块所有者" >> .github/CODEOWNERS
            echo "/blog/apps/comments/ @${{ github.repository_owner }}" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 配置文件所有者" >> .github/CODEOWNERS
            echo "/blog/config/ @${{ github.repository_owner }}" >> .github/CODEOWNERS
            echo "" >> .github/CODEOWNERS
            echo "# 工作流文件所有者" >> .github/CODEOWNERS
            echo "/.github/workflows/ @${{ github.repository_owner }}" >> .github/CODEOWNERS
            
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .github/CODEOWNERS
            git commit -m "chore: 添加CODEOWNERS文件"
            git push
          fi 